### ISSUE TITLE
If the first skill added to a character is Defend, their defense box isn't getting updated

### ISSUE THREAD

**Issue by johnlamping** [epic-power-rpg/roll20#87]
To reproduce:
   Make a new character
   Give it a skill, name that skill Defend, and set it to DX-3, and give it 0 expertise.
   The defense box doesn't update
   Adjust the character's DX.
   The defense box still doesn't update.

**Comment by jazeee** [comment]
Hmm, it seems like it only works if there's a row before it, and only gets recalculated if you change a value.

**Comment by jazeee** [comment]
Doesn't work:
![image](https://user-images.githubusercontent.com/5629800/218289844-b586f0b6-b0fb-4097-9037-7efb9a62ceaa.png)

Works:
![image](https://user-images.githubusercontent.com/5629800/218289852-7f10c633-6376-4999-82dd-99196edfc645.png)

**Comment by jazeee** [comment]
The issue seems to have been around since before afcc9ebd9eed85a3691c6968b050fef2e88eb05d
which is before I reworked parry
![image](https://user-images.githubusercontent.com/5629800/218289970-c7732fdc-566e-4fb2-90da-54bc2282a5b5.png)
![image](https://user-images.githubusercontent.com/5629800/218289976-7c6fce13-fca4-4c45-9277-7207ee9e8810.png)

**Comment by johnlamping** [comment]
Yes, the issue predates all the stuff you have done, Jaz. It's got to be my
bad.

**Comment by jazeee** [comment]
Turns out there are several cases of treating 0 index as false.
Fixing now.

**Comment by johnlamping** [comment]
I was just reading the code, and completely missed that.
